# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import worker_pb2 as proto_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """WorkerService defines the gRPC service for job queue workers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestJob = channel.unary_unary(
                '/worker.WorkerService/RequestJob',
                request_serializer=proto_dot_worker__pb2.JobRequest.SerializeToString,
                response_deserializer=proto_dot_worker__pb2.Job.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/worker.WorkerService/CompleteJob',
                request_serializer=proto_dot_worker__pb2.JobResult.SerializeToString,
                response_deserializer=proto_dot_worker__pb2.CompleteResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """WorkerService defines the gRPC service for job queue workers
    """

    def RequestJob(self, request, context):
        """RequestJob allows workers to pull jobs from the queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """CompleteJob allows workers to report job completion with results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestJob,
                    request_deserializer=proto_dot_worker__pb2.JobRequest.FromString,
                    response_serializer=proto_dot_worker__pb2.Job.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=proto_dot_worker__pb2.JobResult.FromString,
                    response_serializer=proto_dot_worker__pb2.CompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """WorkerService defines the gRPC service for job queue workers
    """

    @staticmethod
    def RequestJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/RequestJob',
            proto_dot_worker__pb2.JobRequest.SerializeToString,
            proto_dot_worker__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/CompleteJob',
            proto_dot_worker__pb2.JobResult.SerializeToString,
            proto_dot_worker__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
