# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/worker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/worker.proto\x12\x06worker\"\x0c\n\nJobRequest\"}\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12)\n\x07headers\x18\x03 \x03(\x0b\x32\x18.worker.Job.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\",\n\tJobResult\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"#\n\x10\x43ompleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\rWorkerService\x12-\n\nRequestJob\x12\x12.worker.JobRequest\x1a\x0b.worker.Job\x12:\n\x0b\x43ompleteJob\x12\x11.worker.JobResult\x1a\x18.worker.CompleteResponseB.Z,github.com/PAFFx/job-poll-queue/proto/workerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/PAFFx/job-poll-queue/proto/worker'
  _globals['_JOB_HEADERSENTRY']._loaded_options = None
  _globals['_JOB_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_JOBREQUEST']._serialized_start=30
  _globals['_JOBREQUEST']._serialized_end=42
  _globals['_JOB']._serialized_start=44
  _globals['_JOB']._serialized_end=169
  _globals['_JOB_HEADERSENTRY']._serialized_start=123
  _globals['_JOB_HEADERSENTRY']._serialized_end=169
  _globals['_JOBRESULT']._serialized_start=171
  _globals['_JOBRESULT']._serialized_end=215
  _globals['_COMPLETERESPONSE']._serialized_start=217
  _globals['_COMPLETERESPONSE']._serialized_end=252
  _globals['_WORKERSERVICE']._serialized_start=254
  _globals['_WORKERSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
